name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  rust-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: https://github.com/Swatinem/rust-cache@v2
      - run: cargo clippy -- -W clippy::pedantic
      - run: cargo build --verbose
      - run: cargo test --verbose
